In [1]:
import pandas as pd

customers = pd.read_csv("dim_customer.csv")
products = pd.read_csv("dim_product.csv")
sales = pd.read_csv("fact_sales.csv")

In [2]:
print(customers.shape)

(10000, 14)

In [3]:
print(products.shape)

(2000, 11)

In [4]:
print(sales.shape)

(43525, 18)

In [5]:
print(customers.columns)

Index(['customer_id', 'name', 'email', 'gender', 'city', 'signup_date',
       'total_orders', 'total_spent', 'avg_order_value', 'last_order_date',
       'recency_days', 'frequency', 'monetary', 'customer_segment'],
      dtype='str')

In [6]:
print(products.columns)

Index(['product_id', 'product_name', 'category', 'brand', 'price', 'rating',
       'total_orders', 'total_sales', 'total_quantity', 'total_profit',
       'avg_selling_price'],
      dtype='str')

In [7]:
print(sales.columns)

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'order_year',
       'order_month', 'quantity', 'revenue', 'cost', 'profit', 'margin_pct',
       'order_status', 'payment_method', 'delivery_days', 'delivery_status',
       'category', 'brand', 'delayed'],
      dtype='str')

In [10]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])
customers['last_order_date'] = pd.to_datetime(customers['last_order_date'])
sales['order_date'] = pd.to_datetime(sales['order_date'])

In [11]:
print(customers[['signup_date', 'last_order_date']].dtypes)
print(sales[['order_date']].dtypes)

signup_date        datetime64[us]
last_order_date    datetime64[us]
dtype: object
order_date    datetime64[us]
dtype: object

In [13]:
customers[['signup_date', 'last_order_date']].head()

  signup_date last_order_date
0  2025-03-13      2024-04-25
1  2024-03-05      2024-12-24
2  2025-07-07      2025-10-21
3  2024-03-07      2025-09-10
4  2025-01-29      2025-01-19

In [14]:
sales[['order_date']].head()

  order_date
0 2025-09-09
1 2025-09-09
2 2025-09-09
3 2025-09-09
4 2025-04-15

In [15]:
customers.head()

,customer_id,name,email,gender,city,signup_date,total_orders,total_spent,avg_order_value,last_order_date,recency_days,frequency,monetary,customer_segment
0,U000001,Angel Hill,donaldgarcia@example.net,Other,New Roberttown,2025-03-13,1,1392.889954,1392.889954,2024-04-25,726,1,1392.889954,At Risk
1,U000002,Jesse Guzman,jennifermiles@example.com,Male,South Bridget,2024-03-05,4,1808.149981,452.037495,2024-12-24,483,4,1808.149981,At Risk
2,U000003,Adam Shaffer,jpeterson@example.org,Male,Curtisfurt,2025-07-07,3,1153.009981,384.336660,2025-10-21,182,3,1153.009981,At Risk
3,U000004,Melanie Munoz,blairamanda@example.com,Other,New Kellystad,2024-03-07,3,7620.839881,2540.279960,2025-09-10,223,3,7620.839881,At Risk
4,U000005,Janet Williams,kendragalloway@example.org,Female,South Joshuastad,2025-01-29,1,12.660000,12.660000,2025-01-19,457,1,12.660000,At Risk

In [16]:
products.head()

,product_id,product_name,category,brand,price,rating,total_orders,total_sales,total_quantity,total_profit,avg_selling_price
0,1.0,Astra Be,Clothing,Astra,157.889999,4.08,19,3789.360016,24,1136.808026,157.890000
1,2.0,NeoTech Someone,Groceries,NeoTech,21.459999,3.87,26,901.319962,42,270.395988,21.459999
2,3.0,Acme Discuss,Sports,Acme,265.369995,3.46,24,9022.579834,34,2706.773950,265.369995
3,4.0,Nimbus South,Electronics,Nimbus,541.409973,4.14,17,12452.429504,23,3735.728937,541.409976
4,5.0,Astra Capital,Home & Kitchen,Astra,198.000000,3.97,22,7128.000000,36,2138.400000,198.000000

In [17]:
sales.head()

,order_id,customer_id,product_id,order_date,order_year,order_month,quantity,revenue,cost,profit,margin_pct,order_status,payment_method,delivery_days,delivery_status,category,brand,delayed
0,O00000001,U009310,1758.0,2025-09-09,2025,9,2,16.139999,11.298000,4.842000,0.3,processing,UPI,6,Delivered,Pet Supplies,Everest,1
1,O00000001,U009310,1119.0,2025-09-09,2025,9,1,74.080002,51.856001,22.224001,0.3,processing,UPI,6,Delivered,Beauty,Nimbus,1
2,O00000001,U009310,1794.0,2025-09-09,2025,9,1,576.969971,403.878979,173.090991,0.3,processing,UPI,6,Delivered,Automotive,Willow,1
3,O00000001,U009310,1038.0,2025-09-09,2025,9,1,22.469999,15.729000,6.741000,0.3,processing,UPI,6,Delivered,Books,Nimbus,1
4,O00000002,U003247,859.0,2025-04-15,2025,4,1,422.220001,295.554001,126.666000,0.3,completed,UPI,2,Delivered,Electronics,Pulse,0

In [18]:
print(customers.isnull().sum())

customer_id            0
name                   0
email                  0
gender                 0
city                   0
signup_date            0
total_orders           0
total_spent            0
avg_order_value        0
last_order_date     1365
recency_days           0
frequency              0
monetary               0
customer_segment       0
dtype: int64

In [19]:
print(products.isnull().sum())

product_id           0
product_name         0
category             0
brand                0
price                0
rating               0
total_orders         0
total_sales          0
total_quantity       0
total_profit         0
avg_selling_price    0
dtype: int64

In [20]:
print(sales.isnull().sum())

order_id           0
customer_id        0
product_id         0
order_date         0
order_year         0
order_month        0
quantity           0
revenue            0
cost               0
profit             0
margin_pct         0
order_status       0
payment_method     0
delivery_days      0
delivery_status    0
category           0
brand              0
delayed            0
dtype: int64

In [23]:
#CLTV = Customer Lifetime Value
customers['cltv'] = customers['avg_order_value'] * customers['frequency']

In [24]:
customers[['customer_id', 'cltv']].head()

  customer_id         cltv
0     U000001  1392.889954
1     U000002  1808.149981
2     U000003  1153.009981
3     U000004  7620.839881
4     U000005    12.660000

In [26]:
customers.to_csv("customer_upgrade.csv", index=False)

In [27]:
sales['order_month'] = sales['order_date'].dt.to_period('M')

In [28]:
sales[['customer_id','order_date','order_month']].head()

  customer_id order_date order_month
0     U009310 2025-09-09     2025-09
1     U009310 2025-09-09     2025-09
2     U009310 2025-09-09     2025-09
3     U009310 2025-09-09     2025-09
4     U003247 2025-04-15     2025-04

In [31]:
#Tracking Customer Activity Across Order Month and Cohort Month (customer first purchase month) 
sales['cohort_month'] = sales.groupby('customer_id')['order_month'].transform('min')
sales[['customer_id','order_month','cohort_month']].head(20)

   customer_id order_month cohort_month
0      U009310     2025-09      2025-05
1      U009310     2025-09      2025-05
2      U009310     2025-09      2025-05
3      U009310     2025-09      2025-05
4      U003247     2025-04      2024-04
5      U003247     2025-04      2024-04
6      U003247     2025-04      2024-04
7      U003247     2025-04      2024-04
8      U007252     2025-04      2024-04
9      U007252     2025-04      2024-04
10     U007252     2025-04      2024-04
11     U008986     2025-10      2024-06
12     U008986     2025-10      2024-06
13     U008986     2025-10      2024-06
14     U008537     2024-11      2024-11
15     U008537     2024-11      2024-11
16     U008537     2024-11      2024-11
17     U003449     2024-10      2024-09
18     U003449     2024-10      2024-09
19     U003449     2024-10      2024-09

In [32]:
#cohort index
sales['cohort_index'] = (
    (sales['order_month'].dt.year - sales['cohort_month'].dt.year) * 12
    + (sales['order_month'].dt.month - sales['cohort_month'].dt.month)
    + 1
)

sales[['customer_id', 'cohort_month', 'order_month', 'cohort_index']].head(10)

  customer_id cohort_month order_month  cohort_index
0     U009310      2025-05     2025-09             5
1     U009310      2025-05     2025-09             5
2     U009310      2025-05     2025-09             5
3     U009310      2025-05     2025-09             5
4     U003247      2024-04     2025-04            13
5     U003247      2024-04     2025-04            13
6     U003247      2024-04     2025-04            13
7     U003247      2024-04     2025-04            13
8     U007252      2024-04     2025-04            13
9     U007252      2024-04     2025-04            13

In [34]:
cohort_data = sales.groupby(['cohort_month', 'cohort_index'])['customer_id'].nunique().reset_index()
cohort_data.head(20)

   cohort_month  cohort_index  customer_id
0       2024-01             1          844
1       2024-01             2           72
2       2024-01             3           76
3       2024-01             4           68
4       2024-01             5           61
5       2024-01             6           75
6       2024-01             7           77
7       2024-01             8           61
8       2024-01             9           57
9       2024-01            10           58
10      2024-01            11           86
11      2024-01            12           70
12      2024-01            13           75
13      2024-01            14           69
14      2024-01            15           69
15      2024-01            16           66
16      2024-01            17           77
17      2024-01            18           72
18      2024-01            19           79
19      2024-01            20           74

In [35]:
cohort_pivot = cohort_data.pivot(index='cohort_month', columns='cohort_index', values='customer_id')
cohort_pivot

cohort_index,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,22,23
cohort_month,,,,,,,,,,,,,,,,,,,,,
2024-01,844.0,72.0,76.0,68.0,61.0,75.0,77.0,61.0,57.0,58.0,...,69.0,69.0,66.0,77.0,72.0,79.0,74.0,75.0,69.0,40.0
2024-02,711.0,73.0,71.0,64.0,53.0,73.0,66.0,68.0,70.0,56.0,...,58.0,58.0,62.0,50.0,65.0,66.0,62.0,55.0,40.0,NaN
2024-03,771.0,72.0,55.0,69.0,67.0,50.0,67.0,77.0,70.0,74.0,...,61.0,70.0,72.0,75.0,60.0,62.0,61.0,31.0,NaN,NaN
2024-04,678.0,59.0,60.0,50.0,58.0,64.0,71.0,46.0,48.0,69.0,...,78.0,50.0,56.0,57.0,61.0,54.0,28.0,NaN,NaN,NaN
2024-05,617.0,59.0,49.0,57.0,59.0,40.0,58.0,41.0,53.0,49.0,...,56.0,54.0,54.0,44.0,55.0,22.0,NaN,NaN,NaN,NaN
2024-06,545.0,54.0,40.0,48.0,46.0,52.0,36.0,48.0,34.0,48.0,...,47.0,53.0,56.0,53.0,20.0,NaN,NaN,NaN,NaN,NaN
2024-07,541.0,47.0,43.0,45.0,42.0,37.0,44.0,58.0,45.0,35.0,...,48.0,37.0,49.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN
2024-08,462.0,31.0,45.0,49.0,38.0,44.0,39.0,44.0,51.0,39.0,...,29.0,45.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,413.0,32.0,35.0,40.0,24.0,31.0,33.0,40.0,40.0,28.0,...,33.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,383.0,24.0,29.0,28.0,41.0,36.0,33.0,24.0,36.0,29.0,...,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11,319.0,26.0,23.0,27.0,28.0,18.0,26.0,28.0,32.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12,333.0,29.0,21.0,33.0,20.0,32.0,27.0,19.0,32.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-01,296.0,22.0,22.0,32.0,32.0,30.0,25.0,31.0,32.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02,239.0,27.0,19.0,16.0,22.0,29.0,19.0,18.0,20.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03,246.0,31.0,19.0,23.0,18.0,20.0,14.0,28.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-04,200.0,13.0,14.0,19.0,23.0,14.0,10.0,11.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-05,196.0,29.0,25.0,12.0,16.0,22.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-06,179.0,7.0,25.0,10.0,17.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-07,174.0,13.0,8.0,13.0,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08,152.0,14.0,13.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09,156.0,10.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10,139.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
retention = cohort_pivot.divide(cohort_pivot.iloc[:, 0], axis=0) * 100
retention = retention.round(2)
retention

cohort_index,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,22,23
cohort_month,,,,,,,,,,,,,,,,,,,,,
2024-01,100.0,8.53,9.00,8.06,7.23,8.89,9.12,7.23,6.75,6.87,...,8.18,8.18,7.82,9.12,8.53,9.36,8.77,8.89,8.18,4.74
2024-02,100.0,10.27,9.99,9.00,7.45,10.27,9.28,9.56,9.85,7.88,...,8.16,8.16,8.72,7.03,9.14,9.28,8.72,7.74,5.63,NaN
2024-03,100.0,9.34,7.13,8.95,8.69,6.49,8.69,9.99,9.08,9.60,...,7.91,9.08,9.34,9.73,7.78,8.04,7.91,4.02,NaN,NaN
2024-04,100.0,8.70,8.85,7.37,8.55,9.44,10.47,6.78,7.08,10.18,...,11.50,7.37,8.26,8.41,9.00,7.96,4.13,NaN,NaN,NaN
2024-05,100.0,9.56,7.94,9.24,9.56,6.48,9.40,6.65,8.59,7.94,...,9.08,8.75,8.75,7.13,8.91,3.57,NaN,NaN,NaN,NaN
2024-06,100.0,9.91,7.34,8.81,8.44,9.54,6.61,8.81,6.24,8.81,...,8.62,9.72,10.28,9.72,3.67,NaN,NaN,NaN,NaN,NaN
2024-07,100.0,8.69,7.95,8.32,7.76,6.84,8.13,10.72,8.32,6.47,...,8.87,6.84,9.06,3.70,NaN,NaN,NaN,NaN,NaN,NaN
2024-08,100.0,6.71,9.74,10.61,8.23,9.52,8.44,9.52,11.04,8.44,...,6.28,9.74,4.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,100.0,7.75,8.47,9.69,5.81,7.51,7.99,9.69,9.69,6.78,...,7.99,4.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,100.0,6.27,7.57,7.31,10.70,9.40,8.62,6.27,9.40,7.57,...,3.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11,100.0,8.15,7.21,8.46,8.78,5.64,8.15,8.78,10.03,8.78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12,100.0,8.71,6.31,9.91,6.01,9.61,8.11,5.71,9.61,12.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-01,100.0,7.43,7.43,10.81,10.81,10.14,8.45,10.47,10.81,8.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02,100.0,11.30,7.95,6.69,9.21,12.13,7.95,7.53,8.37,3.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03,100.0,12.60,7.72,9.35,7.32,8.13,5.69,11.38,2.44,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-04,100.0,6.50,7.00,9.50,11.50,7.00,5.00,5.50,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-05,100.0,14.80,12.76,6.12,8.16,11.22,2.55,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-06,100.0,3.91,13.97,5.59,9.50,3.91,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-07,100.0,7.47,4.60,7.47,3.45,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08,100.0,9.21,8.55,0.66,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09,100.0,6.41,3.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10,100.0,3.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
retention_reset = retention.reset_index()

retention_long = retention_reset.melt(
    id_vars='cohort_month',
    var_name='cohort_index',
    value_name='retention_rate'
)

retention_long['cohort_month'] = retention_long['cohort_month'].astype(str)

retention_long = retention_long.sort_values(
    by=['cohort_month', 'cohort_index']).reset_index(drop=True)

retention_long.to_csv("cohort_analysis.csv", index=False)

retention_long.head(20)

   cohort_month cohort_index  retention_rate
0       2024-01            1          100.00
1       2024-01            2            8.53
2       2024-01            3            9.00
3       2024-01            4            8.06
4       2024-01            5            7.23
5       2024-01            6            8.89
6       2024-01            7            9.12
7       2024-01            8            7.23
8       2024-01            9            6.75
9       2024-01           10            6.87
10      2024-01           11           10.19
11      2024-01           12            8.29
12      2024-01           13            8.89
13      2024-01           14            8.18
14      2024-01           15            8.18
15      2024-01           16            7.82
16      2024-01           17            9.12
17      2024-01           18            8.53
18      2024-01           19            9.36
19      2024-01           20            8.77

In [41]:
#monthly summary (monthly revenue,profit,order trend)
monthly_summary = (
    sales
    .groupby(['order_year', 'order_month'], as_index=False)
    .agg(
        total_orders=('order_id', 'nunique'),
        total_customers=('customer_id', 'nunique'),
        total_revenue=('revenue', 'sum'),
        total_profit=('profit', 'sum'),
        total_quantity=('quantity', 'sum')
    )
)

monthly_summary['avg_order_value'] = (
    monthly_summary['total_revenue'] / monthly_summary['total_orders']
)

monthly_summary.head()

,order_year,order_month,total_orders,total_customers,total_revenue,total_profit,total_quantity,avg_order_value
0,2024,2024-01,881,844,543120.429240,162936.128995,2662,616.481759
1,2024,2024-02,814,783,513712.789653,154113.835681,2534,631.096793
2,2024,2024-03,950,920,541213.259558,162363.977396,2830,569.698168
3,2024,2024-04,928,889,545624.459689,163687.338247,2867,587.957392
4,2024,2024-05,907,856,552700.819844,165810.245190,2748,609.372458

In [42]:
monthly_summary.to_csv("monthly_summary.csv",index =False)

In [43]:
monthly_summary = monthly_summary.sort_values(['order_year', 'order_month']).reset_index(drop=True)

rolling_metrics = monthly_summary.copy()

rolling_metrics['rolling_3m_revenue'] = (
    rolling_metrics['total_revenue']
    .rolling(window=3, min_periods=1)
    .sum()
)

rolling_metrics['rolling_3m_profit'] = (
    rolling_metrics['total_profit']
    .rolling(window=3, min_periods=1)
    .sum()
)

rolling_metrics['rolling_3m_orders'] = (
    rolling_metrics['total_orders']
    .rolling(window=3, min_periods=1)
    .sum()
)

rolling_metrics.head()

,order_year,order_month,total_orders,total_customers,total_revenue,total_profit,total_quantity,avg_order_value,rolling_3m_revenue,rolling_3m_profit,rolling_3m_orders
0,2024,2024-01,881,844,543120.429240,162936.128995,2662,616.481759,5.431204e+05,162936.128995,881.0
1,2024,2024-02,814,783,513712.789653,154113.835681,2534,631.096793,1.056833e+06,317049.964676,1695.0
2,2024,2024-03,950,920,541213.259558,162363.977396,2830,569.698168,1.598046e+06,479413.942072,2645.0
3,2024,2024-04,928,889,545624.459689,163687.338247,2867,587.957392,1.600551e+06,480165.151324,2692.0
4,2024,2024-05,907,856,552700.819844,165810.245190,2748,609.372458,1.639539e+06,491861.560833,2785.0

In [44]:
rolling_metrics.to_csv("rolling_metrics.csv", index=False)

In [45]:
events = pd.read_csv("events.csv")
events['event_timestamp'] = pd.to_datetime(events['event_timestamp'])

events.head()

    event_id  user_id product_id event_type            event_timestamp
0  E00000001  U009798    P001393       cart 2025-07-08 14:28:55.893919
1  E00000002  U005881    P000669       view 2025-10-19 23:00:44.067982
2  E00000003  U006348    P001404       view 2025-05-09 07:02:42.256662
3  E00000004  U002664    P000400       cart 2025-07-19 22:47:07.019634
4  E00000005  U005776    P000392       view 2024-10-24 10:20:33.602165

In [46]:
funnel_data = (
    events.groupby('event_type', as_index=False)
    .agg(total_users=('user_id', 'nunique'))
)

funnel_data

  event_type  total_users
0       cart         6994
1   purchase         3281
2       view         9961
3   wishlist         5504

In [53]:
import pandas as pd

events = pd.read_csv("events.csv")
events['event_timestamp'] = pd.to_datetime(events['event_timestamp'])

events['event_type'] = events['event_type'].str.lower().str.strip()

views = events.loc[events['event_type'] == 'view', 'user_id'].nunique()
wishlist = events.loc[events['event_type'] == 'wishlist', 'user_id'].nunique()
carts = events.loc[events['event_type'] == 'cart', 'user_id'].nunique()
purchases = events.loc[events['event_type'] == 'purchase', 'user_id'].nunique()

funnel_data = pd.DataFrame({
    'stage': ['view', 'wishlist', 'cart', 'purchase'],
    'users': [views, wishlist, carts, purchases]
})

# adjusted funnel values
funnel_data['users'] = funnel_data['users'].cummin()

funnel_data['conversion_from_previous'] = [
    100,
    (funnel_data.loc[1, 'users'] / funnel_data.loc[0, 'users'] * 100) if funnel_data.loc[0, 'users'] > 0 else 0,
    (funnel_data.loc[2, 'users'] / funnel_data.loc[1, 'users'] * 100) if funnel_data.loc[1, 'users'] > 0 else 0,
    (funnel_data.loc[3, 'users'] / funnel_data.loc[2, 'users'] * 100) if funnel_data.loc[2, 'users'] > 0 else 0
]

funnel_data['conversion_from_view'] = [
    100,
    (funnel_data.loc[1, 'users'] / funnel_data.loc[0, 'users'] * 100) if funnel_data.loc[0, 'users'] > 0 else 0,
    (funnel_data.loc[2, 'users'] / funnel_data.loc[0, 'users'] * 100) if funnel_data.loc[0, 'users'] > 0 else 0,
    (funnel_data.loc[3, 'users'] / funnel_data.loc[0, 'users'] * 100) if funnel_data.loc[0, 'users'] > 0 else 0
]

funnel_data['conversion_from_previous'] = funnel_data['conversion_from_previous'].round(2)
funnel_data['conversion_from_view'] = funnel_data['conversion_from_view'].round(2)

funnel_data.to_csv("funnel_data.csv", index=False)
print(funnel_data)

      stage  users  conversion_from_previous  conversion_from_view
0      view   9961                    100.00                100.00
1  wishlist   5504                     55.26                 55.26
2      cart   5504                    100.00                 55.26
3  purchase   3281                     59.61                 32.94

In [55]:
#review_summary

reviews = pd.read_csv("reviews.csv")

review_summary = reviews.groupby('product_id', as_index=False).agg(
    avg_rating=('rating', 'mean'),
    total_reviews=('review_id', 'count')
)

review_summary['avg_rating'] = review_summary['avg_rating'].round(2)

review_summary.to_csv("review_summary.csv", index=False)

print(review_summary.head(30))

   product_id  avg_rating  total_reviews
0     P000001        4.20              5
1     P000002        3.22              9
2     P000003        3.30             10
3     P000004        3.00              7
4     P000005        4.14              7
5     P000006        4.00              9
6     P000007        3.08             13
7     P000008        3.78              9
8     P000009        3.00             10
9     P000010        3.71              7
10    P000011        3.57              7
11    P000012        3.71              7
12    P000013        3.40              5
13    P000014        4.33              6
14    P000015        3.50              6
15    P000016        3.17              6
16    P000017        4.20              5
17    P000018        4.00             11
18    P000019        3.86              7
19    P000021        3.67              9
20    P000022        4.00              6
21    P000023        3.14              7
22    P000024        3.20              5
23    P000025        3.40              5
24    P000026        3.29              7
25    P000027        3.57              7
26    P000028        3.82             11
27    P000029        3.14              7
28    P000030        3.00              7
29    P000031        3.38              8